### ISSUE TITLE
SOS: 403 error on Amazon S3 

### ISSUE THREAD

**Issue by akosbalasko** [baileyherbert/utimes#21]
Hi @baileyherbert !

My CI/CD breaks becase I've got 403 error when I want to download utimes from here: https://node-utimes.s3.amazonaws.com/4.1.1/Release/utimes-v4.1.1-electron-v9.4-darwin-x64.tar.gz

Could you please check the visibility of the published packages? 

Thank you very much!

**Comment by baileyherbert** [comment]
Hi @akosbalasko!

I believe electron has special requirements for native addons and needs them to be rebuilt specifically for electron itself. We can see that this is at least what it's attempting to do, because `electron-v9.4` is in the name of the file it's trying to download. I don't build specifically for electron.

I will first ask you to upgrade to the latest version of `utimes` (5.x) as the binaries have been greatly simplified and are now hosted under the GitHub release – this alone might fix the issue. There are no breaking changes that will affect you, just keep in mind that Node v10+ is now required.

Apparently https://github.com/electron-userland/electron-builder was created to solve issues like this, it can rebuild the package for your electron version on the fly, but I've never used it. I'll look into whether I can publish electron binaries myself, but it won't be quick.

**Comment by akosbalasko** [comment]
Hi @baileyherbert !
Thanks for the quick response! I don't really understand that magic behind, but the version upgrade did the trick. Thank you!

**Comment by baileyherbert** [comment]
Great! I gave your build logs a look and it seems my earlier suspicion was correct – my old binary names were too verbose, and it was including your electron version in the binary name, which would never exist. It was therefore trying to build the binary from scratch but failing due to a different error. 

The new binaries in v5 are much more concise so your electron-builder can get what it needs. :)

Cheers!

**Comment by akosbalasko** [comment]
Oh, get it, thanks for the explanation! Have a nice evening!
