### ISSUE TITLE
Do not follow sym links

### ISSUE THREAD

**Issue by AlttiRi** [baileyherbert/utimes#8]
How about to add an option to do not follow symbolic links and to apply changes on a symbolic link?
Like it does [`lutimes`](https://nodejs.org/api/fs.html#fs_fspromises_lutimes_path_atime_mtime).

---

UPD. Or, for example:
```js
import {utimes, lutimes} from "utimes";
```

**Comment by baileyherbert** [comment]
This would be a great addition.

It will be simple to add this feature for Windows – we just need to add the `FILE_FLAG_OPEN_REPARSE_POINT` flag in the `CreateFileW` call to grab handles for symbolic links instead of their targets. Linux is also easy, we can use the `fs.lutimes` function directly.

I'll need to investigate how this can be done on mac OS though! I'm now wondering if the existing call to `setattrlist` is already applying the timestamps to symbolic links rather than their targets. I don't have access to an Apple device and they don't like to make their OS available for virtual machines, so this might take me some time.

I will work on this when I can. Thanks! :smile:
